package mvc;

import beans.BarriereEntreeBean;
import beans.BarriereSortieBean;
import beans.ParkingBean;
import entity.BarriereEntreeEntity;
import entity.BarriereSortieEntity;
import entity.ParkingEntity;
import generated.parking.BarriereEntree;
import generated.parking.BarriereSortie;
import generated.parking.Parking;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;
import javax.ejb.embeddable.EJBContainer;
import javax.naming.Context;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author anatole
 */
public class MainFrame extends javax.swing.JFrame implements Observer{
    
    EJBContainer container;
    
    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
        container = EJBContainer.createEJBContainer();
        updateSaves();
    }
    
    private void updateSaves() {
        state_number_comboBox.removeAllItems();
        Context namingContext = container.getContext();
        try {
            BarriereEntreeBean beBean = (BarriereEntreeBean) namingContext.lookup("java:global/classes/BarriereEntreeBean");
            for(BarriereEntreeEntity beE : beBean.getSaves()){
                state_number_comboBox.addItem(beE.getId());
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de persistence (chargement des sauvegardes).");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        parkingstate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        carnumber = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        statedoorentry = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        statedoorexit = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        entervisiteur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enteremploye = new javax.swing.JButton();
        getout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        load_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        state_number_comboBox = new javax.swing.JComboBox();

        jLabel6.setText("Etat parking:");

        jLabel7.setText("Plein");

        jLabel8.setText("Nombre voitures:");

        jLabel9.setText("100");

        jLabel10.setText("Etat parking:");

        jLabel11.setText("Plein");

        jLabel12.setText("Nombre voitures:");

        jLabel13.setText("100");

        jTextField1.setText("jTextField1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setText("Simulation");

        jLabel15.setText("Etat parking:");

        parkingstate.setText("Plein");

        jLabel17.setText("Nombre voiture:");

        carnumber.setText("100");

        jLabel19.setText("Barrière entrée:");

        statedoorentry.setText("Fermer");

        jLabel21.setText("Barrière sortie:");

        statedoorexit.setText("Fermer");

        entervisiteur.setText("Faire entrer visiteur");

        jLabel1.setText("Contrôle");

        enteremploye.setText("Faire entrer employé");

        getout.setText("Faire sortir voiture");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Etat"));

        save_button.setText("Sauver");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        load_button.setText("Charger");
        load_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_buttonActionPerformed(evt);
            }
        });

        jLabel3.setText("n° :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(state_number_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(load_button)
                        .addComponent(save_button)))
                .addGap(36, 36, 36))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {load_button, save_button});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(save_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(load_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(state_number_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(parkingstate)
                                .addGap(97, 97, 97)
                                .addComponent(carnumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(statedoorentry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statedoorexit)
                                .addGap(24, 24, 24)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(entervisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(getout, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(98, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(226, 226, 226))
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(enteremploye, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkingstate)
                    .addComponent(carnumber)
                    .addComponent(statedoorentry)
                    .addComponent(statedoorexit))
                .addGap(28, 28, 28)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entervisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enteremploye, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        Context namingContext = container.getContext();
        
        try {
        // sauvegarde de BarriereEntree
            BarriereEntreeBean bEBean = (BarriereEntreeBean) namingContext.lookup("java:global/classes/BarriereEntreeBean");
            bEBean.saveState(BarriereEntree.getInstance());
        // sauvegarde de BarriereSortie
            BarriereSortieBean bSBean = (BarriereSortieBean) namingContext.lookup("java:global/classes/BarriereSortieBean");
            bSBean.saveState(BarriereSortie.getInstance());
        // sauvegarde de Parking
            ParkingBean pBean = (ParkingBean) namingContext.lookup("java:global/classes/ParkingBean");
            pBean.saveState(Parking.getInstance());
            
        // sauvegarde des 3 entités réussie
            JOptionPane.showMessageDialog(null, "Etat sauvegardé.");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de persistence (sauvegarde).");
        }
        
        updateSaves();
    }//GEN-LAST:event_save_buttonActionPerformed

    private void load_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_buttonActionPerformed
        Context namingContext = container.getContext();
        
        try {
            String selectedItem = state_number_comboBox.getSelectedItem().toString();
        // chargement de BarriereEntree
            BarriereEntreeBean bEBean = (BarriereEntreeBean) namingContext.lookup("java:global/classes/BarriereEntreeBean");
            BarriereEntreeEntity loadedBEE = bEBean.loadState(Integer.parseInt(selectedItem));
            if (loadedBEE != null){
                BarriereEntree.getInstance().setState(loadedBEE.getState());
                if (loadedBEE.getState().equals("open"))
                    entervisiteur.doClick();
            } else {
                JOptionPane.showMessageDialog(null, "Impossible de charger l'état "+selectedItem+" de BarriereEntree.");
            }
        // chargement de BarriereSortie
            BarriereSortieBean bSBean = (BarriereSortieBean) namingContext.lookup("java:global/classes/BarriereSortieBean");
            BarriereSortieEntity loadedBSE = bSBean.loadState(Integer.parseInt(selectedItem));
            if (loadedBSE != null){
                BarriereSortie.getInstance().setState(loadedBSE.getState());
                if (loadedBSE.getState().equals("open"))
                    getout.doClick();
            } else {
                JOptionPane.showMessageDialog(null, "Impossible de charger l'état "+selectedItem+" de BarriereSortie.");
            }
        // chargement de Parking
            ParkingBean pBean = (ParkingBean) namingContext.lookup("java:global/classes/ParkingBean");
            ParkingEntity loadedPE = pBean.loadState(Integer.parseInt(selectedItem));
            if (loadedPE != null){
                Parking.getInstance().setNbPlace(loadedPE.getNbPlace());
                Parking.getInstance().setCurrentNumber(loadedPE.getCurrentNumber());
            } else {
                JOptionPane.showMessageDialog(null, "Impossible de charger l'état "+selectedItem+" de Parking.");
            }
            
        // chargement des 3 entités réussi
            update(null, BarriereEntree.getInstance());
            update(null, BarriereSortie.getInstance());
            update(null, Parking.getInstance());
            JOptionPane.showMessageDialog(null, "Etat "+selectedItem+" restauré.");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de persistence (chargement).");
        }
            
    }//GEN-LAST:event_load_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public JButton getEnterEmploye()
    {
        return enteremploye;
    }

    public JButton getEnterVisiteur()
    {
        return entervisiteur;
    }

    public JButton getOut()
    {
        return getout;
    }    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carnumber;
    private javax.swing.JButton enteremploye;
    private javax.swing.JButton entervisiteur;
    private javax.swing.JButton getout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton load_button;
    private javax.swing.JLabel parkingstate;
    private javax.swing.JButton save_button;
    private javax.swing.JComboBox state_number_comboBox;
    private javax.swing.JLabel statedoorentry;
    private javax.swing.JLabel statedoorexit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {        
        if(o1 instanceof BarriereEntree)
        {
            BarriereEntree tmp = (BarriereEntree) o1;
            
            if(tmp.getState().equals("close"))
            {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                       statedoorentry.setText("Fermée");
                    }
                    });              
            }
            else
            {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                       statedoorentry.setText("Ouverte");
                    }
                });
            }
        }
        else if(o1 instanceof Parking)
        {
            Parking tmp = (Parking) o1;
            
            if(tmp.isPlein())
                parkingstate.setText("Plein");
            else
                parkingstate.setText("Libre");
            
            carnumber.setText(String.valueOf(tmp.getVehiculeNumber()));
        }
        else if(o1 instanceof BarriereSortie)
        {
            BarriereSortie tmp = (BarriereSortie) o1;

            if(tmp.getState().equals("close"))
            {
                SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                  statedoorexit.setText("Fermée");
                }
                });              
            }
            else
            {
                SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                  statedoorexit.setText("Ouverte");
                }
                });
            }   
        }
    }
    
    /**
     * Add controller to all button
     * @param controller 
     */
    public void addController(ActionListener controller)
    {
        enteremploye.addActionListener(controller);
        entervisiteur.addActionListener(controller);
        getout.addActionListener(controller);
    }
}
